id: PB1458D48
initial_creation_type: input
source_metadata:
  title: Trulshik Rinpoche Series
  language: fr
  description: Texts by and about Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö ('khrul
    zhig ngag dbang chos kyi blo gros, 1924–2011), one of the teachers of His Holiness
    the Fourteenth Dalai Lama.
  volume:
    179cb369ca19474386c64c7bb5941f3a:
      title: Advice for Retreat
      parent: Advice
    537c568881be4c10bc5adbb49dd9a388:
      title: Advice for Tenzin Jamchen
      parent: Advice
    8efdbe04fa8e450a8a8577aedcd6341c:
      title: Advice in Four Lines
      parent: Advice
    ecfb0090de77487ab7dc29486695951e:
      title: A Prayer for Translators
      parent: Aspiration Prayers
    28a0e8377b1648138649471cdd984d7d:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    f503d86f11c34fcd8f9e4d0e9d51f536:
      title: Prayer of the View, Meditation and Conduct
      parent: Aspiration Prayers
    849588a0c6694e40bbdbaea89a99018a:
      title: Profound Prayer of Aspiration
      parent: Aspiration Prayers
    ad9a459a5bf94421a29334e1c9225547:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Guru Yoga
    c3661b730e534a648c985b359cbec47d:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    c73d2d76b0f84237aeb3db6d877ecdbe:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    6bb565aacca9485480edaf5d68f6e61f:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    b3ca1049b407448dbde17b62476e9697:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    0e4ffa72401b403d8a8e54372433a4f3:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
    851a708d7c0f47eda28035d27007fa8d:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    261a02e9cfd14510a954ec6c09899a54:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Long Life Prayers
    6cd6fd139d1740a2983d9b5c22343064:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    d68829848387416c8afe0aa54b7be1a6:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Long Life Prayers
    cdc1677161974ef6b49d153c30352c23:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Long Life Prayers
    9c4dfb068b29454cba4d62e0c8dbfed5:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Long Life Prayers
    32304c7f298a4ece92c7eb72cf3a7701:
      title: The Attainment of Immortality
      parent: Long Life Prayers
    091f223150f84b74b81ca334dc46099b:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    43b35dfcc3a44f62b7bbebcac6f7c323:
      title: Verses of Homage
      parent: Praise
    053df3b41fb6442789921708d376e741:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    e116603ab8484a0099f71757a92dc3e5:
      title: A Record of the Successive Incarnations
      parent: Prayers
    a7f0966b7b8c41c98a58b2b405676a78:
      title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
        of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
      parent: Prayers
    6c0195f50aca442683e3612340c3a9f1:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    5e966c6e5d6841ef973dee7cb7a918d2:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:52:59.291617'
last_modified_at: '2022-03-01T01:52:59.291621'
